// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env["DATABASE_URL"] ||
  `mysql://${encodeURIComponent(process.env["DB_USER"] || "root")}:${encodeURIComponent(
    process.env["DB_PASSWORD"] || "password",
  )}@${process.env["DB_HOST"] || "localhost"}:${process.env["DB_PORT"] || "3306"}/${
    process.env["DB_NAME"] || "ai_learning_platform"
  }`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
